---
kind: pipeline
type: docker
name: coding-standard-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_s3

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phpunit-scality-php7.1-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_external_s3
    version: daily-master-qa

- name: install-app-files_external_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server/apps/files_external_s3
  - composer install -n --no-progress

- name: install-extra-apps
  pull: always
  image: owncloudci/php:7.1
  commands:
  - git clone https://github.com/owncloud/files_primary_s3.git /var/www/owncloud/testrunner/apps/files_primary_s3
  - cp -r /var/www/owncloud/testrunner/apps/files_primary_s3 /var/www/owncloud/server/apps/
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:l

- name: setup-server-files_external_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-scality
  pull: always
  image: owncloudci/php:7.1
  commands:
  - wait-for-it -t 600 scality:8000
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/scality.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server

- name: scality-config
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cp tests/drone/configs/config.scality.php tests/unit/config.php

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: scality
  pull: always
  image: owncloudci/scality-s3server
  environment:
    HOST_NAME: scality
    SCALITY_ACCESS_KEY_ID: owncloud123456
    SCALITY_SECRET_ACCESS_KEY: secret123456

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1

---
kind: pipeline
type: docker
name: phpunit-scality-php7.2-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_external_s3
    version: daily-master-qa

- name: install-app-files_external_s3
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server/apps/files_external_s3
  - composer install -n --no-progress

- name: install-extra-apps
  pull: always
  image: owncloudci/php:7.2
  commands:
  - git clone https://github.com/owncloud/files_primary_s3.git /var/www/owncloud/testrunner/apps/files_primary_s3
  - cp -r /var/www/owncloud/testrunner/apps/files_primary_s3 /var/www/owncloud/server/apps/
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:l

- name: setup-server-files_external_s3
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-scality
  pull: always
  image: owncloudci/php:7.1
  commands:
  - wait-for-it -t 600 scality:8000
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/scality.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server

- name: scality-config
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cp tests/drone/configs/config.scality.php tests/unit/config.php

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: scality
  pull: always
  image: owncloudci/scality-s3server
  environment:
    HOST_NAME: scality
    SCALITY_ACCESS_KEY_ID: owncloud123456
    SCALITY_SECRET_ACCESS_KEY: secret123456

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1

---
kind: pipeline
type: docker
name: phpunit-scality-php7.3-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_external_s3
    version: daily-master-qa

- name: install-app-files_external_s3
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server/apps/files_external_s3
  - composer install -n --no-progress

- name: install-extra-apps
  pull: always
  image: owncloudci/php:7.3
  commands:
  - git clone https://github.com/owncloud/files_primary_s3.git /var/www/owncloud/testrunner/apps/files_primary_s3
  - cp -r /var/www/owncloud/testrunner/apps/files_primary_s3 /var/www/owncloud/server/apps/
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:l

- name: setup-server-files_external_s3
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-scality
  pull: always
  image: owncloudci/php:7.1
  commands:
  - wait-for-it -t 600 scality:8000
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/scality.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server

- name: scality-config
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cp tests/drone/configs/config.scality.php tests/unit/config.php

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: scality
  pull: always
  image: owncloudci/scality-s3server
  environment:
    HOST_NAME: scality
    SCALITY_ACCESS_KEY_ID: owncloud123456
    SCALITY_SECRET_ACCESS_KEY: secret123456

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1

---
kind: pipeline
type: docker
name: phpunit-ceph-php7.1-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_external_s3
    version: daily-master-qa

- name: install-app-files_external_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server/apps/files_external_s3
  - composer install -n --no-progress

- name: install-extra-apps
  pull: always
  image: owncloudci/php:7.1
  commands:
  - git clone https://github.com/owncloud/files_primary_s3.git /var/www/owncloud/testrunner/apps/files_primary_s3
  - cp -r /var/www/owncloud/testrunner/apps/files_primary_s3 /var/www/owncloud/server/apps/
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:l

- name: setup-server-files_external_s3
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-ceph
  pull: always
  image: owncloudci/php:7.1
  commands:
  - wait-for-it -t 600 ceph:80
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/ceph.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server
  - ./apps/files_primary_s3/tests/drone/create-bucket.sh

- name: ceph-config
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cp tests/drone/configs/config.ceph.php tests/unit/config.php

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: ceph
  pull: always
  image: owncloudci/ceph:tag-build-master-jewel-ubuntu-16.04
  environment:
    CEPH_DEMO_ACCESS_KEY: owncloud123456
    CEPH_DEMO_SECRET_KEY: secret123456
    CEPH_DEMO_UID: owncloud
    NETWORK_AUTO_DETECT: 4
    RGW_NAME: ceph

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1

---
kind: pipeline
type: docker
name: phpunit-ceph-php7.2-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_external_s3
    version: daily-master-qa

- name: install-app-files_external_s3
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server/apps/files_external_s3
  - composer install -n --no-progress

- name: install-extra-apps
  pull: always
  image: owncloudci/php:7.2
  commands:
  - git clone https://github.com/owncloud/files_primary_s3.git /var/www/owncloud/testrunner/apps/files_primary_s3
  - cp -r /var/www/owncloud/testrunner/apps/files_primary_s3 /var/www/owncloud/server/apps/
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:l

- name: setup-server-files_external_s3
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-ceph
  pull: always
  image: owncloudci/php:7.1
  commands:
  - wait-for-it -t 600 ceph:80
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/ceph.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server
  - ./apps/files_primary_s3/tests/drone/create-bucket.sh

- name: ceph-config
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cp tests/drone/configs/config.ceph.php tests/unit/config.php

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: ceph
  pull: always
  image: owncloudci/ceph:tag-build-master-jewel-ubuntu-16.04
  environment:
    CEPH_DEMO_ACCESS_KEY: owncloud123456
    CEPH_DEMO_SECRET_KEY: secret123456
    CEPH_DEMO_UID: owncloud
    NETWORK_AUTO_DETECT: 4
    RGW_NAME: ceph

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1

---
kind: pipeline
type: docker
name: phpunit-ceph-php7.3-sqlite

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/files_external_s3

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/files_external_s3
    version: daily-master-qa

- name: install-app-files_external_s3
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server/apps/files_external_s3
  - composer install -n --no-progress

- name: install-extra-apps
  pull: always
  image: owncloudci/php:7.3
  commands:
  - git clone https://github.com/owncloud/files_primary_s3.git /var/www/owncloud/testrunner/apps/files_primary_s3
  - cp -r /var/www/owncloud/testrunner/apps/files_primary_s3 /var/www/owncloud/server/apps/
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - composer install
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_primary_s3
  - php occ a:l

- name: setup-server-files_external_s3
  pull: always
  image: owncloudci/php:7.3
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e files_external_s3
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: setup-ceph
  pull: always
  image: owncloudci/php:7.1
  commands:
  - wait-for-it -t 600 ceph:80
  - cd /var/www/owncloud/server/apps/files_primary_s3
  - cp tests/drone/ceph.config.php /var/www/owncloud/server/config
  - cd /var/www/owncloud/server
  - ./apps/files_primary_s3/tests/drone/create-bucket.sh

- name: ceph-config
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cp tests/drone/configs/config.ceph.php tests/unit/config.php

- name: phpunit-tests
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-unit-dbg

- name: codecov-upload
  pull: always
  image: plugins/codecov:2
  settings:
    paths:
    - tests/output/clover.xml
    token:
      from_secret: codecov_token

services:
- name: ceph
  pull: always
  image: owncloudci/ceph:tag-build-master-jewel-ubuntu-16.04
  environment:
    CEPH_DEMO_ACCESS_KEY: owncloud123456
    CEPH_DEMO_SECRET_KEY: secret123456
    CEPH_DEMO_UID: owncloud
    NETWORK_AUTO_DETECT: 4
    RGW_NAME: ceph

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

depends_on:
- coding-standard-php7.1

---
kind: pipeline
type: docker
name: chat-notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify-rocketchat
  pull: always
  image: plugins/slack:1
  settings:
    channel: builds
    webhook:
      from_secret: private_rocketchat

trigger:
  ref:
  - refs/tags/**
  - refs/heads/master
  status:
  - success
  - failure

depends_on:
- phpunit-scality-php7.1-sqlite
- phpunit-scality-php7.2-sqlite
- phpunit-scality-php7.3-sqlite
- phpunit-ceph-php7.1-sqlite
- phpunit-ceph-php7.2-sqlite
- phpunit-ceph-php7.3-sqlite

...
